version: '3.9'
services:
  ee.postgres:
    container_name: "ee.postgres"
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - ee_net
    ports:
      - "5432:5432"
      - "5433:5432"

networks:
  ee_net:
    external: true